### ISSUE TITLE
Should mocking the same path, with different headers, return different results?

### ISSUE THREAD

**Issue by peter-mouland** [ldabiralai/simulado#2]
The following script produces the desired output below:

``` javascript
var Simulado = require('simulado');
var SimuladoServer = require('simulado/server');
var personas = require('../test/support/fixtures');

new SimuladoServer().start(7001)

Object.keys(personas).forEach(function(persona){
  Simulado.mock({
    path: '/service-checks/' + persona + '/restrictions',
    method: 'GET',
    status: 200,
    headers: { 'X-Billing-Account-Number': persona},
    response: personas[persona]
  }, function(err, lastRequestMade) {
    err && console.log(err)
  });


  Simulado.mock({
    path: '/service-checks',
    method: 'POST',
    status: 200,
    headers: { 'X-Billing-Account-Number': persona},
    response: personas[persona]
  }, function(err, lastRequestMade) {
    err && console.log(err)
  });

})
```

<img width="415" alt="screen shot 2016-01-18 at 12 24 07" src="https://cloud.githubusercontent.com/assets/1727939/12391274/6a3263ae-bdde-11e5-938b-ea2d22cd6485.png">

only hitting /service-checks always returns the same mocked response, no matter what headers i send through.

I expected to be able to send different headers to return different mocked responses.

**Comment by krow-ten** [comment]
The ability "... to send different headers to return different mocked responses" would be a useful feature no doubt. However the headers syntax that is currently there is for defining the headers that Simulado will set on the response.

**Comment by peter-mouland** [comment]
> closing this due to lack of interest (read: tidying up my outstanding issues!)
