### ISSUE TITLE
Remove callbacks

### ISSUE THREAD

**Issue by ldabiralai** [ldabiralai/simulado#21]
As part of #20 (and 2.6.0) we started accepting promises and deprecated callbacks.

We should take some time to completely remove callbacks and switch over to promises.

**Comment by krow-ten** [comment]
or even async/await?

**Comment by ldabiralai** [comment]
Async/await is syntactical sugar for promises and only very recent versions of node have started to support it. I don't think we should move to async/await for the core of simulado just yet as it'll likely raise more issues for end users than it'll fix.

Although, I do agree that it'd be nice to move to async/await in the future.

**Comment by alexjfno1** [comment]
The v3 version does not use callbacks anymore.
