### ISSUE TITLE
Transpile ES6 into ES5

### ISSUE THREAD

**Issue by alexjfno1** [ldabiralai/simulado#25]

**Comment by krow-ten** [comment]
what do you mean by this exactly? Is this for the simulado server or for the embedded api?

**Comment by alexjfno1** [comment]
We probably want to distribute the package as ES5 rather than ES6 so the end user doesn't have to transpile it themselves.

**Comment by krow-ten** [comment]
I think most users would be using a version of node higher than 0.10

**Comment by ldabiralai** [comment]
I don't think it's worth distributing simulado in es5 unless there's specific demand for it as it'll add overhead to the code/build/deployment etc.
