### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by bdo** [ldabiralai/simulado#38]
We would require this for our project as all our environments are currently running using https.

**Comment by bdo** [comment]
I'm actually thinking that if we could embed simulado in our app, that would be even simpler. Maybe by exposing the express app itself ?

**Comment by ldabiralai** [comment]
Added in https://github.com/ldabiralai/simulado/compare/900bf1024752c2c4bbd9e4e885cf8c9cf3d269c4...4795fa387e0400dddf498579ca9e5285e8509bc5 @bdo!

I think this is probably the cleanest solution as it means we don't have to expose the user to the express server. All they need to do is pass in the path to the key & cert and it should serve on https as desired.

Give it a go and let me know if anything's missing!
