### ISSUE TITLE
Run prettier after each merge

### ISSUE THREAD

**Issue by ldabiralai** [ldabiralai/simulado#61]
This should take simplify the pr process, we could do this two ways:

- during builds on master we can run prettier and commit and push with [ci skip] (depending on ci)
or
- during builds on master we can run prettier and rebase into the previous commit so we don't pollute the commit log with prettier commits, this might be a bit risky though

**Comment by alexjfno1** [comment]
I think I would prefer it if it ran in the branch before merging to master. Then if it did break something it would be caught before merging to master

**Comment by ldabiralai** [comment]
I think that would be preferred too, but I wasn't sure how to achieve that and keep the PR process simple for others.

Issue with the first is that contributors would start having random commits pop-up while developing and would become out of sync with the branch.

And the second would cause the branches to diverge/duplicate commits as the commit hashes would change after CI rebased.

**Comment by alexjfno1** [comment]
Ideally it would run prettier just before squash and merge. What about https://github.com/prettier/prettier#option-1-lint-staged

**Comment by alexjfno1** [comment]
Another option could be to use https://github.com/prettier/prettier#prettierchecksource--options and have a step on cirlce ci that fails unless you format the files. This would stop pr's being merged without formatting and doesn't require and commits or pushes by the ci.

**Comment by ldabiralai** [comment]
Going to close this as it's partially solved by #63, happy to reopen if it becomes something we want to automate further!
