### ISSUE TITLE
No documentation for resetting the mocks

### ISSUE THREAD

**Issue by christemple** [ldabiralai/simulado#7]
This is more of a reminder for myself than anything, there is no documentation in the README on how to  reset the mocks.

Looked at the source code and a `DELETE /reset` seemed to have done the job, will try to update later.

**Comment by krow-ten** [comment]
POST to /reset will do it
If you POST a body of { "path": _path_, "method": _http_method_ } then it will only reset that particular mocked endpoint.

**Comment by alexjfno1** [comment]
This will be solved in Version 3
