### ISSUE TITLE
Rename addMock to setMock

### ISSUE THREAD

**Issue by leozero** [ldabiralai/simulado#84]
The method name "addMock" is confusing because it can "update / replace" a mock with the same path.

Renaming this method can improve the comprehension of it.

**Comment by alexjfno1** [comment]
So this seems to make sense so we will add the `setMock` function and add a depreciation warning to `addMock`.

I will also raise an issue to remove `addMock` in `V4`.

**Comment by leozero** [comment]
Thanks @alexjfno1

**Comment by ldabiralai** [comment]
Released in 3.3.0 @leozero
